# Gruvbox Material Dark theme for lazygit
gui:
  nerdFontsVersion: "3"
  showIcons: true
  showFileTree: true
  mouseEvents: false
  language: en
  border: rounded
  timeFormat: ''
  shortTimeFormat: ''
  expandFocusedSidePanel: true
  screenMode: normal
  scrollHeight: 1
  animateExplosion: true
  commitAuthorShortLength: 1
  commitAuthorLongLength: 1
  commitHashLength: 6
  showBottomLine: true
  showPanelJumps: true
  authorColors:
    'Is Ma': '#e78a4e'
    '*': '#7daea3'
  theme:
    activeBorderColor:
      - '#a9b665'
      - bold
    inactiveBorderColor:
      - '#3c3836'
    optionsTextColor:
      - '#d8a657'
    selectedLineBgColor:
      - '#3c3836'
    selectedRangeBgColor:
      - '#5a524c'
    cherryPickedCommitBgColor:
      - '#5a524c'
    cherryPickedCommitFgColor:
      - '#a9b665'
    unstagedChangesColor:
      - '#ea6962'
    defaultFgColor:
      - '#ddc7a1'
    searchingActiveBorderColor:
      - '#e78a4e'
      - bold

git:
  autoFetch: true
  autoRefresh: true
  autoStageResolvedConflicts: true
  branchLogCmd: git log --oneline --graph --decorate --color=always {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --all --color=always --oneline --decorate
  mainBranches:
    - main
  parseEmoji: false
  log:
    order: topo-order
    showGraph: always
    showWholeGraph: true

os:
  shellFunctionsFile: /home/rich/is-ma/home/targets/bash/custom_bash.sh
  edit: '/home/rich/.cargo/bin/hx {{filename}}'
  open: 'xdg-open {{filename}} >/dev/null'

skipAmendWarning: true
skipDiscardChangeWarning: true
skipStashWarning: true
skipNoStagedFilesWarning: true
skipRewordInEditorWarning: true
skipSwitchWorktreeOnCheckoutWarning: true

update:
  method: background
  days: 7
