inherits = "gruvbox_material_dark_hard"

"ui.selection" = { bg = "#5a524c" }          # bg3
"ui.linenr" = { fg = "#3c3836" }             # bg2
"ui.linenr.selected" = { fg = "#a9b665" }    # green
"ui.window" = { fg = "#282828" }             # bg1
"ui.statusline" = { fg = "#ddc7a1", bg = "#282828" }              # fg1, bg1
"ui.statusline.normal" = { fg = "#a9b665", bg = "#282828", modifiers = ["bold"] }  # green, bg1
"ui.statusline.insert" = { fg = "#e78a4e", bg = "#282828", modifiers = ["bold"] }  # orange, bg1
"ui.statusline.select" = { fg = "#d3869b", bg = "#282828", modifiers = ["bold"] }  # purple, bg1
"ui.cursorline.primary" = { bg = "#282828" }          # bg1
