# don't let ripgrep vomit really long lines to my terminal
--max-columns=150

# add my 'web' type
--type-add
web:*.{html,css,js,jsx,ts,tsx,htmx}

# ignore case if search is in lowercase
--smart-case

# follow symlinks
--follow

# colors (default)
--color=auto

